language: csharp

solution: Newq.sln

sudo: false

cache:
  directories:
    - $TRAVIS_BUILD_DIR/packages

install:
  - nuget restore Newq.sln
  - nuget install xunit.runners -Version 1.9.1 -OutputDirectory testrunner

notifications:
  email: false
